version: '3.9'

services:
  backend:
    container_name: api
    build:
      context: ./api
      dockerfile: api.Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - sqlite-data:/app/db
    depends_on:
      - frontend
    networks:
      - app-network

  frontend:
    container_name: ui
    build:
      context: ./ui
      dockerfile: ui.Dockerfile
    ports:
      - "3000:80"
    networks:
      - app-network

volumes:
  sqlite-data:
    driver: local

networks:
  app-network:

