# Generated by Django 5.1.4 on 2024-12-30 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="asset",
            unique_together={("id", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="portfolio",
            unique_together={("id", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="price",
            unique_together={("id", "date", "asset")},
        ),
        migrations.AlterUniqueTogether(
            name="weight",
            unique_together={("id", "date", "asset", "portfolio")},
        ),
    ]
