# Generated by Django 5.1.4 on 2025-01-10 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_date_alter_price_date_alter_quantity_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.asset')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='portfolio.date')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.portfolio')),
            ],
            options={
                'unique_together': {('id', 'date', 'asset', 'portfolio')},
            },
        ),
    ]
