# Generated by Django 5.1.4 on 2024-12-30 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_alter_asset_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="asset",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="portfolio",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="asset",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
